In [1]:
import pandas as pd
import numpy as np

# Question 1

In [2]:
np.__version__

'1.22.1'

In [22]:
df=pd.read_csv('data/data.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

# Question 2

In [23]:
df.shape[0]

11914

# Question 3

In [24]:
df.Make.value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

# Question 4

In [25]:
df.Make.value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [32]:
df[df.Make=='Audi']['Model'].drop_duplicates().shape

(34,)

# Question 5 

In [7]:
df.isnull().any().sum()

5

# Question 6 

In [8]:
df['Engine Cylinders'].median()

6.0

In [9]:
#df['Engine Cylinders'].value_counts().idxmax()
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [10]:
df['Engine Cylinders']=df['Engine Cylinders'].fillna(value=df['Engine Cylinders'].mode())

In [11]:
df['Engine Cylinders'].median()

6.0

In [12]:
# no, it has not changed

# Question 7

## 7.1

In [13]:
df = df[ df.Make == 'Lotus' ]

## 7.1

In [14]:
df = df[["Engine HP", "Engine Cylinders"]]

# 7.3

In [15]:
df = df.drop_duplicates()
df

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

## 7.5

In [16]:
X = np.array(df)
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

## 7.6

In [17]:
XTX = np.dot(X.T, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

## 7.7

In [18]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

## 7.8

In [19]:
w = np.dot( np.dot( np.linalg.inv(XTX), X.T ), y ) 
w

array([  4.59494481, -63.56432501])

## 7.9

In [20]:
w[0]

4.594944810094551